# Generated by Django 3.2.9 on 2021-12-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_generator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='sort_form',
            new_name='short_form',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='sort_form',
            new_name='short_form',
        ),
        migrations.AddField(
            model_name='profile',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
