# Generated by Django 3.2.9 on 2022-02-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course_question',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
